site_name: Dan's Cyber Stuff
nav:
  - Home: index.md
  - CWES Study Notes:
    - Contents: cwes-study-notes/index.md
    - Web Penetration Tester Course Module Notes:
      - Web Requests: cwes-study-notes/web-requests.md
      - Introduction to Web Applications: cwes-study-notes/introduction-to-web-applications.md
      - Using Web Proxies: cwes-study-notes/using-web-proxies.md
      - Information Gathering Web Edition: cwes-study-notes/information-gathering-web-edition.md
      - Web Fuzzing: cwes-study-notes/web-fuzzing.md
      - JavaScript Deobfuscation: cwes-study-notes/javascript-deobfuscation.md
      - Cross-Site Scripting (XSS): cwes-study-notes/cross-site-scripting-(xss).md
      - SQL Injection Fundamentals: cwes-study-notes/sql-injection-fundamentals.md
      - SQLMap Essentials: cwes-study-notes/sqlmap-essentials.md
      - Command Injections: cwes-study-notes/command-injections.md
      - File Upload Attacks: cwes-study-notes/file-upload-attacks.md
      - Server-side Attacks: cwes-study-notes/server-side-attacks.md
      - Login Brute Forcing: cwes-study-notes/login-brute-forcing.md
      - Broken Authentication: cwes-study-notes/broken-authentication.md
      - Web Attacks: cwes-study-notes/web-attacks.md
      - File Inclusion: cwes-study-notes/file-inclusion.md
      - Attacking GraphQL: cwes-study-notes/attacking-graphql.md
      - API Attacks: cwes-study-notes/api-attacks.md
      - Attacking Common Applications: cwes-study-notes/attacking-common-applications.md
      - Bug Bounty Hunting Process: cwes-study-notes/bug-bounty-hunting-process.md
    - Additional Cheat Sheets:
      - FTP: cwes-study-notes/ftp-cheat.md
      - Gobuster: cwes-study-notes/gobuster-cheat.md

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - content.code.copy

plugins:
  - search
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      linenums: true
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
